#!/usr/bin/perl

#
# Converts TM files generated by lookupAllPaths.c into trafficfiles needed for
# TeXCP simulation
#

#
# Command: 
#

$ind = 0;

while(<>){
  chop;

  #clear the lines a little bit
  next if(/Demands/);
  next if(/^#/);
  s/[\=\[\]]//g;
  s/\s+$//g;
  s/\s+;$//g;
  s/^\s+//g;
  next if(length($_) == 0);

  #sanity check that the lines make sense
  @vec = split(/\s+/);
  if($ind == 0){
    $numlines = $#vec;
  }else {
    die "bad line [$_]\n" if($#vec != $numlines);
  }

  $lineout = join(" ", @vec);

  #just dump them out
  printf ("%s\n", $lineout);
  $ind ++;
}
